Relative_url/Relative_url/urls.py
from django.contrib import admin
from django.urls import path, include
from basicApp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basicApp/',include('basicApp.urls')),
    path('admin/', admin.site.urls),
]

Relative_url/basicApp/urls.py
from django.urls import path
from basicApp import views


app_name = 'basicApp'


urlpatterns = [
    path('Relative/',views.Relative,name='Relative'),
    path('other/',views.other,name='other'),
]

Relative_url/basicApp/models.py
from django.db import models

# Create your models here.

Relative_url/basicApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'basicApp/index.html')

def other(request):
    return render(request,'basicApp/other.html')

def Relative(request):
    return render(request,'basicApp/Relative_url.html')

Relative_url/templates/basicApp/Relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative Url Page</h1>
    <a href="{% url 'basicApp:other' %}">Go to Other page</a>
    <a href="{% url 'index' %}">INDEX</a>
    <a href="{% url 'admin:index' %}">Admin</a>
  </body>
</html>

Relative_url/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navabar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navabar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navabar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navabar-link" href="{% url 'basicApp:other' %}">Other</a></li>
        </ul>

      </div>

    </nav>
    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

Relative_url/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Index Page</h1>
    <h2>This is Index Page</h2>
  {% endblock %}

Relative_url/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other Page</h1>
    <h2>Template Inheritance</h2>
  {% endblock %}